name: bluebuild
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - main
      - test
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/blue-build/cli:latest
      #options: --user root #-v /var/run/docker.sock:/var/run/docker.sock
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - base.yml
    steps:
      # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

      - name: Build Image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          BB_BUILD_PUSH: "true"
          BB_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          BB_USERNAME: ${{ github.actor }}
          BB_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
          BB_REGISTRY_NAMESPACE: ${{ github.repository_owner }}
          BB_REPOSITORY: ${{ github.repository }}
          GH_PR_EVENT_NUMBER: ${{ github.event.number }}
          RECIPE_PATH: ./recipes/recipe.yml
          RUST_LOG_STYLE: always
          CLICOLOR_FORCE: "1"
        run: |
          bluebuild build -v "${RECIPE_PATH}"
